### ISSUE TITLE
How to apply gravity to particle

### ISSUE THREAD

**Issue by dariuspranskus** [rockbite/talos#55]
Hi

Im unable to figure out how to apply gravity in the effect I am creating. I can see that there was a gravity property in Particle node some time ago, but now it has been removed. Also if I try importing libgdx legacy effect, the gravity settings are not being imported.

Could you please advice. Do you have any sample hot to do it.

Thank you very much.

**Comment by azakhary** [comment]
Don't know how missed this. Sorry.
But will answer anyway, maybe someone else needs it.
Gravity node is removed, and best way to do any physics (including gravity) would be to use ForceApplier module in order to calculate multiple forces, and then take it's velocity angle outputs into velocity and angle of particle.

**Comment by Tom-Ski** [comment]
Closing this. Particle can have forces in latest branch, including specifically gravity options.
